name: omni_video_player
description: "A Flutter widget for playing videos from YouTube, Vimeo, assets, and network sources â€” fully customizable and easy to integrate."
version: 3.3.3-beta
homepage: https://github.com/leonardmatasel/omni_video_player
repository: https://github.com/leonardmatasel/omni_video_player
issue_tracker: https://github.com/leonardmatasel/omni_video_player/issues

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

platforms:
  android:
  ios:
  web:

funding:
  - https://github.com/sponsors/leonardmatasel

dependencies:
  flutter:
    sdk: flutter

  media_kit: ^1.2.1
  media_kit_video: ^1.3.1
  media_kit_libs_video: ^1.0.7
  wakelock_plus: ^1.4.0
  synchronized: ^3.4.0

  visibility_detector: ^0.4.0+2
  volume_controller: ^3.4.0
  http: ^1.6.0
  web: ^1.1.1

  youtube_explode_dart: ^3.0.3

  flutter_inappwebview: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  dartdoc: ^9.0.0

flutter:
  assets:
    - assets/youtube_player.html


topics:
  - video
  - youtube
  - vimeo
  - player
  - video-player